name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "*.vcxproj"
      - "*.rc"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "*.vcxproj"
      - "*.rc"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: windows-2025-vs2026

    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build (${{ matrix.configuration }} x64)
        run: |
          msbuild DarkSoulsTracker.vcxproj `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=x64 `
            /p:OutDir=build\${{ matrix.configuration }}\ `
            /p:IntDir=build\${{ matrix.configuration }}\obj\ `
            /v:minimal `
            /nologo

      - name: Upload build artifact
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v7
        with:
          name: dinput8
          path: build\Release\dinput8.dll
          retention-days: 7
